/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package auth_package;


import auth_package.Sign_in;
import java.awt.FileDialog;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



import DB_connection.ConnectDb;
import DB_connection.Auth02;
import DB_connection.Connection_close;
import Ui_02arena.Container;
import java.util.Arrays;

/**
 *
 * @author User
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form New_entrys
     */
    
   Image im; String as;
    int sd,fu,lo,ko;
    public Register() {
        setUndecorated(true);
        initComponents();
        setResizable(false);
        jPanel1.setFocusable(true);
        setLocationRelativeTo(null);
        jLabel8.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        phones = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setForeground(new java.awt.Color(0, 0, 0));
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name.setText("Name");
        name.setBorder(null);
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 210, 20));

        email.setBackground(new java.awt.Color(255, 255, 255));
        email.setForeground(new java.awt.Color(0, 0, 0));
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setText("Email");
        email.setBorder(null);
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 200, 30));

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 50, 40));

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 100, 40));

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setForeground(new java.awt.Color(0, 0, 0));
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setText("Password");
        password.setBorder(null);
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 170, 20));

        phones.setBackground(new java.awt.Color(255, 255, 255));
        phones.setForeground(new java.awt.Color(0, 0, 0));
        phones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phones.setText("Phone");
        phones.setBorder(null);
        phones.setCaretColor(new java.awt.Color(0, 0, 0));
        phones.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phonesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phonesFocusLost(evt);
            }
        });
        phones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phonesKeyTyped(evt);
            }
        });
        jPanel1.add(phones, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 170, 30));

        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 50, 50));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 170, 160));

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 170, 20));

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/visibility.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 30, 30));

        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/private.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/regs.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        // TODO add your handling code here:
        if(name.getText().equals("Name")){
            name.setText("");
        }
    }//GEN-LAST:event_nameFocusLost

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        // TODO add your handling code here:
        if(name.getText().equals("Name")){
            name.setText("");
        }
    }//GEN-LAST:event_nameFocusGained

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
        if(email.getText().equals("Email")){
            email.setText("");
        }
    }//GEN-LAST:event_emailFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        // TODO add your handling code here:
          if(email.getText().equals("Email")){
            email.setText("");
        }
        
    }//GEN-LAST:event_emailFocusLost

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Sign_in f=new Sign_in();
        f.show();
        dispose();
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        if(name.getText().equals("Name")|name.getText().isEmpty()| phones.getText().equals("Phone")|phones.getText().isEmpty() | email.getText().equals("Email")|email.getText().isEmpty() |password.getText().equals("Password")| password.getText().isEmpty())
              new Container().message("Fill all fields");
         else {
              Pattern mask=null;  
              mask=Pattern.compile(".+@.+\\.[a-z]+");
               Matcher matcher=mask.matcher(email.getText());
              
                 if(!matcher.matches())
                   new Container().message("Pls enter a valid email"); 
                 else
                     reg_member();
                   }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
        if( password.getText().equals("Password")){
             password.setText("");
        }
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        // TODO add your handling code here:
          if( password.getText().equals("Password")){
             password.setText("");
        }
    }//GEN-LAST:event_passwordFocusLost

    private void phonesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phonesFocusGained
        // TODO add your handling code here:
        if(phones.getText().equals("Phone")){
            phones.setText(null);
        }
    }//GEN-LAST:event_phonesFocusGained

    private void phonesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phonesFocusLost
        // TODO add your handling code here:
          if(phones.getText().equals("Phone")){
            phones.setText(null);
        }
    }//GEN-LAST:event_phonesFocusLost

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        FileDialog file= new FileDialog(this,"Open",FileDialog.LOAD);
        file.show();
        if(file.getFile()!=null){
             as=(file.getDirectory()+file.getFile());
            Toolkit toolket=Toolkit.getDefaultToolkit();
            Image image=toolket.getImage(as);
            im=image.getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(),Image.SCALE_SMOOTH);
            jLabel5.setIcon(new ImageIcon(im));
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void phonesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonesKeyTyped
        // TODO add your handling code here:
        char in =evt.getKeyChar();
        if(!(Character.isDigit(in))||(in==KeyEvent.VK_BACK_SPACE)||(in==KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_phonesKeyTyped

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_emailActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    jLabel6.setText(password.getText());
    jLabel7.setVisible(false);password.setVisible(false); jLabel8.setVisible(true);
        
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        password.setText(jLabel6.getText());
    jLabel8.setVisible(false);jLabel7.setVisible(true);password.setVisible(true);
       
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phones;
    // End of variables declaration//GEN-END:variables


    
    public void reg_member()  {
      
        Connection connection = null;

      try {

         connection = new ConnectDb().getConnection();
         PreparedStatement ps = connection .prepareStatement("INSERT INTO register_member (valid_user,email,passwords,phone) VALUES (?,?,?,?)");

         ps.setString(1, name.getText().trim()); //name
         ps.setString(2, email.getText().trim()); //email
         String x= new Auth02().encryt(Arrays.toString(password.getPassword()));
         ps.setString(3, x); //password
         ps.setString(4, phones.getText()); //phone
         ps.executeUpdate();
        ps.close();
        new  Container().message("Registed Successfully");
        new Sign_in().show();
        dispose();
  } catch (SQLException e) {
    new  Container().message(e.toString());
  } 

             finally{
             new Connection_close().Connection_terminate(connection);
            }
     

  
    }

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
//        private void Uploaders() {
//        
//         FileInputStream fis= null;
//         try{
//             if(as==null){
//                JOptionPane.showMessageDialog(null, "Error Occured Pls Upload a Picture");
//         } }catch(HeadlessException ex){JOptionPane.showMessageDialog(null, "Error Occured Pls Upload a Picture");
//         }
//     try{
//            fis = new FileInputStream(as);
//            ByteArrayOutputStream bos= new ByteArrayOutputStream();
//            byte[] buf = new byte[1024];
//            try{
//                for(int readNum; (readNum=fis.read(buf)) != -1;){
//                    bos.write(buf, 0, readNum);
//                    System.out.println("read"+readNum+ "byte");
//                }
//            }catch(IOException ex){
//                System.out.println("reading Error"+ex);
//             JOptionPane.showMessageDialog(null, "Error Occured Pls Upload a Picture");
//         }
//            byte[] bytess=  bos.toByteArray();
// 
//            addImage(bytess); 
// }catch(FileNotFoundException e){
//     JOptionPane.showMessageDialog(null, e);
//     System.out.println(e);
//        }
//    }
//        
//        
//        
//     public  static byte[] imageTobyte(File file) throws FileNotFoundException{
//         FileInputStream fis= new FileInputStream(file);
//         ByteArrayOutputStream bos= new ByteArrayOutputStream();
//         byte[] buf = new byte[1024];
//         try{
//             for(int readNum; (readNum=fis.read(buf)) != -1;){
//                 bos.write(buf, 0, readNum);
//                 System.out.println("read"+readNum+ "byte");
//             }
//         }catch(IOException ex){System.out.println("reading Error"+ex);
//         JOptionPane.showMessageDialog(null, "Error Occured Pls try again");
//        }
//
//        byte[] bytess=  bos.toByteArray();
//
//        return bytess;
//        }
//
//  
   










}

